### ISSUE TITLE
Publish the lib on InterSystems Open Exchange?

### ISSUE THREAD

**Issue by evshvarov** [ontariosystems/isclib#8]
Great library, guys!
Make it more visible for the community - publish in [Open Exchange](https://openexchange.intersystems.com/)?

**Comment by ghost** [comment]
It has been submitted and is waiting for approval

**Comment by evshvarov** [comment]
@krmichelos thank you so much! Do you mind to rename the asset to GoISC or GoIRIS?  Just to highlight that it relates to Go

**Comment by ghost** [comment]
It has been published.  The description, readme, and the language details all indicate that it is go, so I think we will stick with the name for now.

**Comment by evshvarov** [comment]
Thank you @krmichelos! It's a bit strange, though, that app named as [iscenv](https://openexchange.intersystems.com/package/iscenv), and the repository as isclib

**Comment by evshvarov** [comment]
Also we recently introduced an option to submit the app on behalf of a company. E.g. you are able to put OntarioSystems name and description on Open Exchange if you want. Check e.g. [InterSystems](https://openexchange.intersystems.com/company/InterSystems-Corporation) entry, or [GeorgeJames](https://openexchange.intersystems.com/company/George-James-Software).  You can find how to submit a company [here](https://community.intersystems.com/post/open-exchange-april-release-companies)

**Comment by ghost** [comment]
> Thank you @krmichelos! It's a bit strange, though, that app named as [iscenv](https://openexchange.intersystems.com/package/iscenv), and the repository as isclib

Yeah, sorry, typing habit.  That is the name of one of the apps that uses the library.  It is fixed now.
